# ğŸ«¦ ê¸°ì¡´ auth-gateì™€ ìƒˆë¡œ ë§Œë“  create-userë¥¼ ëª¨ë‘ ì •ì˜í•©ë‹ˆë‹¤.

[functions.auth-gate]
enabled = true
verify_jwt = true
import_map = "./functions/auth-gate/deno.json"
entrypoint = "./functions/auth-gate/index.ts"

[functions.create-user]
enabled = true
verify_jwt = true
import_map = "./functions/create-user/deno.json"
entrypoint = "./functions/create-user/index.ts"